# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooxc5UCXRmsqy-XQNbjd8hE2MsmNn-Oq
"""

from flask import Flask, render_template, request, redirect, url_for, jsonify
import pickle
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import io
import base64
import sys

app = Flask(__name__)

# Load models and scaler
scaler = pickle.load(open("Models/scaler.pkl", 'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))

# Career class names
class_names = [
    'Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
    'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
    'Banker', 'Writer', 'Accountant', 'Designer',
    'Construction Engineer', 'Game Developer', 'Stock Investor',
    'Real Estate Developer'
]

# Personality test data
holland_questions = {
    "R": ["I enjoy working with machines and tools.", "I like practical tasks.", "I prefer building things."],
    "I": ["I enjoy solving puzzles.", "I like experiments.", "I enjoy analyzing data."],
    "A": ["I enjoy drawing.", "I like expressing through music.", "I enjoy writing."],
    "S": ["I enjoy helping people.", "I like volunteering.", "I enjoy teaching."],
    "E": ["I enjoy leading teams.", "I like persuading others.", "I enjoy organizing."],
    "C": ["I prefer working with numbers.", "I like organized systems.", "I enjoy record-keeping."]
}

personality_info = {
    "R": {"name": "Realistic", "description": "Practical, hands-on", "careers": ["Carpenter", "Electrician"]},
    "I": {"name": "Investigative", "description": "Analytical, problem solver", "careers": ["Scientist", "Engineer"]},
    "A": {"name": "Artistic", "description": "Creative, expressive", "careers": ["Artist", "Writer"]},
    "S": {"name": "Social", "description": "Helpful, nurturing", "careers": ["Teacher", "Nurse"]},
    "E": {"name": "Enterprising", "description": "Leader, persuasive", "careers": ["Entrepreneur", "Manager"]},
    "C": {"name": "Conventional", "description": "Organized, structured", "careers": ["Accountant", "Data Analyst"]}
}

# Career recommendation function
def get_career_recommendations(gender, part_time_job, absence_days, extracurricular_activities,
                              weekly_self_study_hours, math_score, history_score, physics_score,
                              chemistry_score, biology_score, english_score, geography_score,
                              total_score, average_score):
    # Encode categorical variables
    gender_encoded = 1 if gender.lower() == 'female' else 0
    part_time_job_encoded = 1 if part_time_job else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0

    # Create feature array
    feature_array = np.array([[gender_encoded, part_time_job_encoded, absence_days, extracurricular_activities_encoded,
                             weekly_self_study_hours, math_score, history_score, physics_score,
                             chemistry_score, biology_score, english_score, geography_score, total_score,
                             average_score]])

    # Scale features
    scaled_features = scaler.transform(feature_array)

    # Predict using the model
    probabilities = model.predict_proba(scaled_features)

    # Get top three predicted classes along with their probabilities
    top_classes_idx = np.argsort(-probabilities[0])[:3]
    top_classes_names_probs = [(class_names[idx], round(probabilities[0][idx] * 100, 2)) for idx in top_classes_idx]

    return top_classes_names_probs

# Personality test processing
def process_personality_test(data):
    # Initialize scores
    scores = {ptype: 0 for ptype in holland_questions}

    # Calculate scores
    for key, value in data.items():
        try:
            ptype = key.split('_')[0]
            if ptype in scores:
                scores[ptype] += int(value)
        except (ValueError, IndexError):
            continue

    # Find dominant type
    dominant_type = max(scores, key=scores.get)

    # Generate chart
    plt.figure(figsize=(8, 6))
    labels = [personality_info[ptype]['name'] for ptype in scores]
    values = [scores[ptype] for ptype in scores]
    plt.pie(values, labels=labels, autopct='%1.1f%%')

    img_buffer = io.BytesIO()
    plt.savefig(img_buffer, format='png', bbox_inches='tight')
    plt.close()
    img_buffer.seek(0)
    chart_base64 = base64.b64encode(img_buffer.read()).decode('utf-8')

    return {
        "personality": personality_info[dominant_type]["name"],
        "description": personality_info[dominant_type]["description"],
        "careers": personality_info[dominant_type]["careers"],
        "chart": chart_base64,
        "scores": scores
    }

# Routes
@app.route('/')
def home():
    return render_template('home.html')

@app.route('/career', methods=['GET', 'POST'])
def career():
    if request.method == 'POST':
        gender = request.form['gender']
        part_time_job = request.form.get('part_time_job', 'false') == 'true'
        absence_days = int(request.form['absence_days'])
        extracurricular_activities = request.form.get('extracurricular_activities', 'false') == 'true'
        weekly_self_study_hours = int(request.form['weekly_self_study_hours'])
        math_score = int(request.form['math_score'])
        history_score = int(request.form['history_score'])
        physics_score = int(request.form['physics_score'])
        chemistry_score = int(request.form['chemistry_score'])
        biology_score = int(request.form['biology_score'])
        english_score = int(request.form['english_score'])
        geography_score = int(request.form['geography_score'])
        total_score = float(request.form['total_score'])
        average_score = float(request.form['average_score'])

        recommendations = get_career_recommendations(
            gender, part_time_job, absence_days, extracurricular_activities,
            weekly_self_study_hours, math_score, history_score, physics_score,
            chemistry_score, biology_score, english_score, geography_score,
            total_score, average_score
        )

        return render_template('results.html', recommendations=recommendations)

    return render_template('career.html')

@app.route('/personality', methods=['GET', 'POST'])
def personality():
    if request.method == 'POST':
        try:
            data = request.get_json()
            if not data:
                return jsonify({"error": "No data received"}), 400

            results = process_personality_test(data)
            return jsonify(results)
        except Exception as e:
            return jsonify({"error": str(e)}), 500

    return render_template('personality.html', questions=holland_questions)

@app.route('/combined', methods=['GET', 'POST'])
def combined():
    if request.method == 'POST':
        # Process career form
        gender = request.form['gender']
        part_time_job = request.form.get('part_time_job', 'false') == 'true'
        absence_days = int(request.form['absence_days'])
        extracurricular_activities = request.form.get('extracurricular_activities', 'false') == 'true'
        weekly_self_study_hours = int(request.form['weekly_self_study_hours'])
        math_score = int(request.form['math_score'])
        history_score = int(request.form['history_score'])
        physics_score = int(request.form['physics_score'])
        chemistry_score = int(request.form['chemistry_score'])
        biology_score = int(request.form['biology_score'])
        english_score = int(request.form['english_score'])
        geography_score = int(request.form['geography_score'])
        total_score = float(request.form['total_score'])
        average_score = float(request.form['average_score'])

        career_results = get_career_recommendations(
            gender, part_time_job, absence_days, extracurricular_activities,
            weekly_self_study_hours, math_score, history_score, physics_score,
            chemistry_score, biology_score, english_score, geography_score,
            total_score, average_score
        )

        # Process personality test
        personality_data = {}
        for key in request.form:
            if key.startswith(tuple(holland_questions.keys())):
                personality_data[key] = int(request.form[key])

        personality_results = process_personality_test(personality_data)

        return render_template('combined_results.html',
                            career_results=career_results,
                            personality_results=personality_results)

    return render_template('combined.html', questions=holland_questions)

if __name__ == '__main__':
    app.run(debug=True)